-- Script to fix prestataire_id in existing contracts
-- This script helps diagnose and fix the issue where prestataires cannot see their contracts

-- =====================================================
-- PART 1: DIAGNOSTIC - Current state of contracts
-- =====================================================

SELECT '=== ETAT ACTUEL DES CONTRATS ===' as info;
SELECT 
    COUNT(*) as total_contrats,
    SUM(CASE WHEN prestataire_id IS NULL OR prestataire_id = '' THEN 1 ELSE 0 END) as sans_prestataire_id,
    SUM(CASE WHEN prestataire_id IS NOT NULL AND prestataire_id != '' THEN 1 ELSE 0 END) as avec_prestataire_id
FROM contrats;

-- Show contracts without prestataire_id
SELECT '=== CONTRATS SANS PRESTATAIRE_ID ===' as info;
SELECT id, id_contrat, nom_prestataire, prestataire_id, statut
FROM contrats 
WHERE prestataire_id IS NULL OR prestataire_id = ''
ORDER BY nom_prestataire;

-- Show unique prestataire names in contracts (to help with mapping)
SELECT '=== NOMS DE PRESTATAIRES UNIQUES DANS LES CONTRATS ===' as info;
SELECT DISTINCT nom_prestataire, COUNT(*) as nombre_contrats
FROM contrats 
WHERE prestataire_id IS NULL OR prestataire_id = ''
GROUP BY nom_prestataire
ORDER BY nom_prestataire;

-- =====================================================
-- PART 2: CREATE MAPPING TABLE
-- =====================================================

-- Drop table if exists (for clean restart)
DROP TABLE IF EXISTS temp_prestataire_mapping;

-- Create temporary mapping table
CREATE TABLE temp_prestataire_mapping (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom_prestataire VARCHAR(255) NOT NULL,
    keycloak_user_id VARCHAR(255) NOT NULL,
    keycloak_username VARCHAR(255),
    keycloak_email VARCHAR(255),
    notes VARCHAR(500)
);

-- =====================================================
-- PART 3: INSERT MAPPINGS (EDIT THIS SECTION)
-- =====================================================
-- 
-- INSTRUCTIONS:
-- 1. Get the list of Keycloak users with their IDs using the Keycloak Admin Console or API
-- 2. Match each Keycloak user with the corresponding nom_prestataire in the contracts table
-- 3. Insert the mappings below
--
-- To get Keycloak users via API (requires admin token):
-- curl -X GET "http://localhost:8080/admin/realms/Maintenance-DGSI/users" \
--   -H "Authorization: Bearer YOUR_ADMIN_TOKEN"
--

-- Example mappings (REPLACE THESE WITH ACTUAL VALUES FROM YOUR KEYCLOAK):
-- INSERT INTO temp_prestataire_mapping (nom_prestataire, keycloak_user_id, keycloak_username, keycloak_email, notes) VALUES
-- ('Softlink Digital Solutions', 'a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'softlink', 'contact@softlink.bf', 'Mapped via admin'),
-- ('IT Solutions SARL', 'b2c3d4e5-f6a7-8901-bcde-f23456789012', 'itsolutions', 'info@itsolutions.bf', 'Mapped via admin'),
-- ('NetCom', 'c3d4e5f6-a7b8-9012-cdef-345678901234', 'netcom', 'netcom@example.bf', 'Mapped via admin');

-- =====================================================
-- PART 4: VERIFY MAPPINGS BEFORE UPDATE
-- =====================================================

SELECT '=== VERIFICATION DES MAPPINGS ===' as info;
SELECT 
    m.nom_prestataire,
    m.keycloak_user_id,
    m.keycloak_username,
    m.keycloak_email,
    COUNT(c.id) as contrats_a_mettre_a_jour
FROM temp_prestataire_mapping m
LEFT JOIN contrats c ON LOWER(c.nom_prestataire) = LOWER(m.nom_prestataire)
WHERE c.prestataire_id IS NULL OR c.prestataire_id = ''
GROUP BY m.nom_prestataire, m.keycloak_user_id, m.keycloak_username, m.keycloak_email;

-- =====================================================
-- PART 5: UPDATE CONTRACTS (RUN THIS AFTER VERIFYING MAPPINGS)
-- =====================================================

-- Update contracts using the mapping (case-insensitive match)
UPDATE contrats c
SET prestataire_id = (
    SELECT m.keycloak_user_id 
    FROM temp_prestataire_mapping m 
    WHERE LOWER(c.nom_prestataire) = LOWER(m.nom_prestataire)
    LIMIT 1
)
WHERE (c.prestataire_id IS NULL OR c.prestataire_id = '')
AND EXISTS (
    SELECT 1 FROM temp_prestataire_mapping m 
    WHERE LOWER(c.nom_prestataire) = LOWER(m.nom_prestataire)
);

-- =====================================================
-- PART 6: VERIFICATION AFTER UPDATE
-- =====================================================

SELECT '=== VERIFICATION APRES MISE A JOUR ===' as info;
SELECT 
    COUNT(*) as total_contrats,
    SUM(CASE WHEN prestataire_id IS NULL OR prestataire_id = '' THEN 1 ELSE 0 END) as sans_prestataire_id,
    SUM(CASE WHEN prestataire_id IS NOT NULL AND prestataire_id != '' THEN 1 ELSE 0 END) as avec_prestataire_id
FROM contrats;

-- Show contracts that still don't have prestataire_id
SELECT '=== CONTRATS TOUJOURS SANS PRESTATAIRE_ID ===' as info;
SELECT id, id_contrat, nom_prestataire, prestataire_id, statut
FROM contrats 
WHERE prestataire_id IS NULL OR prestataire_id = ''
ORDER BY nom_prestataire;

-- Show contracts with their prestataire_id (sample)
SELECT '=== CONTRATS AVEC PRESTATAIRE_ID (ECHANTILLON) ===' as info;
SELECT id, id_contrat, nom_prestataire, prestataire_id, statut
FROM contrats 
WHERE prestataire_id IS NOT NULL AND prestataire_id != ''
ORDER BY nom_prestataire
LIMIT 10;

-- =====================================================
-- PART 7: CLEANUP (OPTIONAL - RUN AFTER SUCCESSFUL UPDATE)
-- =====================================================

-- Uncomment to drop the temporary table after successful update
-- DROP TABLE IF EXISTS temp_prestataire_mapping;

-- =====================================================
-- PART 8: QUICK FIX FOR SPECIFIC CONTRACT (if needed)
-- =====================================================
-- 
-- If you need to update a specific contract immediately:
-- 
-- UPDATE contrats 
-- SET prestataire_id = 'YOUR_KEYCLOAK_USER_ID'
-- WHERE id = CONTRACT_ID;
-- 
-- Or update by contract ID:
-- 
-- UPDATE contrats 
-- SET prestataire_id = 'YOUR_KEYCLOAK_USER_ID'
-- WHERE id_contrat = 'CTR-0001';
